services:
  postgres:
    image: postgres:alpine
    container_name: postgres_storelink
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - storelink_db:/var/lib/postgresql/data
    networks:
      - storelink
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_storelink
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL} # Your login email for pgAdmin
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD} # Your login password
    volumes:
      - storelink_pgadmin:/var/lib/pgadmin
    networks:
      - storelink
    ports:
      - "9000:80"
  nestjs:
    build:
      context: ../
      dockerfile: ./containers/nestjs/Dockerfile
    image: nestjs:storelink
    container_name: nestjs_storelink
    restart: always
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_PUBLIC=${JWT_PUBLIC}
    volumes:
      - nestjs_volume:/usr/backend
      - /usr/backend/node_modules
    depends_on:
      - postgres
    networks:
      - storelink
    ports:
      - "${PORT}:${PORT}"

networks:
  storelink:
    driver: bridge
    name: storelink

volumes:
  storelink_db:
  storelink_pgadmin:
  nestjs_volume:
    name: nestjs_volume
    driver: local
    driver_opts:
      type: none
      device: ../backend
      o: bind
